using A8_Bandi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shows
{
    public class BroadwayShow
    { 

        public String Name { get; set; }
        public String Theater { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime CloseDate { get; set; }
        public String Runtime { get; set; }

        public static BroadwayShow[] GetShows()
        {
            return new BroadwayShow[]
            {
                new BroadwayShow() { Name = "Mean Girls", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,12,25), CloseDate = new DateTime(2020,1,26), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "The Phantom of the Opera", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,12,18), CloseDate = new DateTime(2020,1,5), Runtime = "2 hours 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Potted Potter", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,12,11), CloseDate = new DateTime(2020,1,19), Runtime = "70 minutes with no intermission" },
                new BroadwayShow() { Name = "Irving Berlin’s White Christmas", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,12,10), CloseDate = new DateTime(2019,12,15), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "The Simon & Garfunkel Story", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,11,19), CloseDate = new DateTime(2019,12,8), Runtime = "2 hours 15 minutes with an intermission" },
                new BroadwayShow() { Name = "Corduroy", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,11,15), CloseDate = new DateTime(2020,1,5), Runtime = "1 hour with no intermission" },
                new BroadwayShow() { Name = "KATHLEEN TURNER: FINDING MY VOICE", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,11,15), CloseDate = new DateTime(2019,11,16), Runtime = "110 minutes including an intermission" },
                new BroadwayShow() { Name = "Latin History for Morons", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,10,29), CloseDate = new DateTime(2019,11,3), Runtime = "110 minutes with no intermission" },
                new BroadwayShow() { Name = "An Evening with C.S. Lewis", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,10,22), CloseDate = new DateTime(2019,11,3), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "Oslo", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,9,10), CloseDate = new DateTime(2019,10,20), Runtime = "2 hours and 45 minutes with an intermission" },
                new BroadwayShow() { Name = "The Band’s Visit", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,9,3), CloseDate = new DateTime(2019,9,15), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "Come From Away", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,7,30), CloseDate = new DateTime(2019,8,18), Runtime = "100 minutes with no intermission" },
                new BroadwayShow() { Name = "Cats", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,7,16), CloseDate = new DateTime(2019,8,4), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Les Misérables", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,7,9), CloseDate = new DateTime(2019,7,27), Runtime = "2 hours 55 minutes with an intermission" },
                new BroadwayShow() { Name = "PJ Masks", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,6,7), CloseDate = new DateTime(2019,6,9), Runtime = "80 minutes with an intermission" },
                new BroadwayShow() { Name = "Falsettos", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,5,28), CloseDate = new DateTime(2019,6,9), Runtime = "2 hours and 40 minutes with an intermission" },
                new BroadwayShow() { Name = "Four Chords and a Gun", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,5,18), CloseDate = new DateTime(2019,6,2), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "Rent", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,5,10), CloseDate = new DateTime(2019,5,19), Runtime = "2 hours and 40 minutes with an intermission" },
                new BroadwayShow() { Name = "Chicago", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,5,7), CloseDate = new DateTime(2019,5,12), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "American Girl Live", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,4,30), CloseDate = new DateTime(2019,5,12), Runtime = "90 minutes plus an intermission" },
                new BroadwayShow() { Name = "Rock of Ages", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,4,23), CloseDate = new DateTime(2019,4,28), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Dein Perry’s Tap Dogs", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,4,16), CloseDate = new DateTime(2019,4,21), Runtime = "75 minutes with no intermission" },
                new BroadwayShow() { Name = "Rain: A Tribute to the Beatles", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,4,14), CloseDate = new DateTime(2019,4,14), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "Jersey Boys", Theater = "Auditorium Theatre", OpenDate = new DateTime(2019,4,2), CloseDate = new DateTime(2019,4,7), Runtime = "2 hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Cruel Intentions: The 90s Musical", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,4,2), CloseDate = new DateTime(2019,4,14), Runtime = "1 hour 50 minutes with an intermission" },
                new BroadwayShow() { Name = "Anastasia", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,3,26), CloseDate = new DateTime(2019,4,7), Runtime = "2 hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "The Choir of Man", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,3,12), CloseDate = new DateTime(2019,3,17), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "A Bronx Tale", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,3,12), CloseDate = new DateTime(2019,3,24), Runtime = "2 hours and 5 minutes with an intermission" },
                new BroadwayShow() { Name = "FRIENDS! The Musical Parody", Theater = "Broadway Playhouse", OpenDate = new DateTime(2019,2,12), CloseDate = new DateTime(2019,3,3), Runtime = "2 hours and 10 minutes with an intermission" },
                new BroadwayShow() { Name = "Dear Evan Hansen", Theater = "James M. Nederlander Theatre", OpenDate = new DateTime(2019,2,12), CloseDate = new DateTime(2019,3,10), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Kinky Boots", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2019,1,22), CloseDate = new DateTime(2019,1,27), Runtime = "2 hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "The Lightning Thief: The Percy Jackson Musical", Theater = "Oriental Theatre", OpenDate = new DateTime(2019,1,8), CloseDate = new DateTime(2019,1,13), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "Fiddler on the Roof", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,12,18), CloseDate = new DateTime(2019,1,6), Runtime = "2 hours and 55 minutes with an intermission" },
                new BroadwayShow() { Name = "Stomp", Theater = "Broadway Playhouse", OpenDate = new DateTime(2018,12,5), CloseDate = new DateTime(2018,12,30), Runtime = "1 hour 45 minutes with no intermission" },
                new BroadwayShow() { Name = "The Play That Goes Wrong", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,12,4), CloseDate = new DateTime(2018,12,16), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "The Book of Mormon", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,11,20), CloseDate = new DateTime(2018,12,2), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Miss Saigon", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,11,13), CloseDate = new DateTime(2018,12,8), Runtime = "2 hour and 40 minutes with an intermission" },
                new BroadwayShow() { Name = "Wild Kratts LIVE 2.0", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,11,11), CloseDate = new DateTime(2018,11,11), Runtime = "90 minutes with an intermission" },
                new BroadwayShow() { Name = "Ken Ludwig’s ‘Twas the Night Before Christmas", Theater = "Broadway Playhouse", OpenDate = new DateTime(2018,11,3), CloseDate = new DateTime(2018,12,30), Runtime = "45 minutes with no intermission" },
                new BroadwayShow() { Name = "Hello, Dolly!", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,10,23), CloseDate = new DateTime(2018,11,17), Runtime = "2 hour and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Roald Dahl’s Charlie and the Chocolate Factory", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,10,2), CloseDate = new DateTime(2018,10,21), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "The Color Purple", Theater = "Auditorium Theatre", OpenDate = new DateTime(2018,7,17), CloseDate = new DateTime(2018,7,29), Runtime = "2 hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "Waitress", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,7,3), CloseDate = new DateTime(2018,7,22), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Heartbreak Hotel", Theater = "Broadway Playhouse", OpenDate = new DateTime(2018,6,30), CloseDate = new DateTime(2018,9,9), Runtime = "2 hours and 15 minutes with an intermission" },
                new BroadwayShow() { Name = "The Cher Show", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,6,12), CloseDate = new DateTime(2018,7,15), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Dirty Dancing", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,5,29), CloseDate = new DateTime(2018,6,3), Runtime = "2 hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "Stories I Only Tell My Friends: Live", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,5,19), CloseDate = new DateTime(2018,5,19), Runtime = "1 hour and 40 minutes" },
                new BroadwayShow() { Name = "Rodgers + Hammerstein’s Cinderella", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,4,27), CloseDate = new DateTime(2018,5,6), Runtime = "2 hours and 30 minutes including intermission" },
                new BroadwayShow() { Name = "On Your Feet!", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,3,21), CloseDate = new DateTime(2018,4,8), Runtime = "2 hours and 15 minutes with an intermission" },
                new BroadwayShow() { Name = "A Taste of Things to Come", Theater = "Broadway Playhouse", OpenDate = new DateTime(2018,3,20), CloseDate = new DateTime(2018,4,29), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "The Magic of Adam Trent", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,3,16), CloseDate = new DateTime(2018,3,17), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "Pretty Woman: The Musical", Theater = "Oriental Theatre", OpenDate = new DateTime(2018,3,13), CloseDate = new DateTime(2018,4,15), Runtime = "2 hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Love Never Dies", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,2,14), CloseDate = new DateTime(2018,3,4), Runtime = "2 hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "The Humans", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2018,1,30), CloseDate = new DateTime(2018,2,11), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "Potted Potter", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,12,13), CloseDate = new DateTime(2018,2,25), Runtime = "80 minutes with no intermission" },
                new BroadwayShow() { Name = "Wicked", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,12,6), CloseDate = new DateTime(2018,1,21), Runtime = "2 hours and 45 minutes with an intermission" },
                new BroadwayShow() { Name = "Beautiful – The Carole King Musical", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,12,5), CloseDate = new DateTime(2018,1,28), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Gobsmacked!", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,12,5), CloseDate = new DateTime(2017,12,10), Runtime = "1 hour and 50 minutes with an intermission" },
                new BroadwayShow() { Name = "Irving Berlin’s White Christmas", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,11,21), CloseDate = new DateTime(2017,12,3), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Ken Ludwig’s ‘Twas the Night Before Christmas", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,11,10), CloseDate = new DateTime(2017,12,31), Runtime = "45 minutes with no intermission" },
                new BroadwayShow() { Name = "Escape to Margaritaville", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,11,9), CloseDate = new DateTime(2017,12,2), Runtime = "2 hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "School of Rock", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,11,1), CloseDate = new DateTime(2017,11,19), Runtime = "Approximately 2 hours and 30 minutes, including one intermission." },
                new BroadwayShow() { Name = "Les Misérables", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,10,11), CloseDate = new DateTime(2017,10,29), Runtime = "2 hours and 55 minutes with an intermission" },
                new BroadwayShow() { Name = "Motown The Musical", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,10,3), CloseDate = new DateTime(2017,10,8), Runtime = "2 hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "90210: The Musical", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,9,13), CloseDate = new DateTime(2017,9,17), Runtime = "1 hour and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "An American in Paris", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,7,25), CloseDate = new DateTime(2017,8,13), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Something Rotten!", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,7,11), CloseDate = new DateTime(2017,7,23), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Rodgers & Hammerstein’s The King and I", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,6,14), CloseDate = new DateTime(2017,7,2), Runtime = "2 hours and 50 minutes with an intermission" },
                new BroadwayShow() { Name = "Rent", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,5,9), CloseDate = new DateTime(2017,5,14), Runtime = "2 hours and 40 minutes with an intermission" },
                new BroadwayShow() { Name = "Disney’s Aladdin", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2017,4,11), CloseDate = new DateTime(2017,9,10), Runtime = "2 hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Rain – A Tribute to the Beatles", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,3,28), CloseDate = new DateTime(2017,4,2), Runtime = "2 hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "Circus 1903 – The Golden Age of Circus", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,3,21), CloseDate = new DateTime(2017,3,26), Runtime = "2 hours and 5 minutes with an intermission" },
                new BroadwayShow() { Name = "The Naked Magicians", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,3,14), CloseDate = new DateTime(2017,3,19), Runtime = "1 hour and 20 minutes with no intermission" },
                new BroadwayShow() { Name = "Hedwig and the Angry Inch", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,3,7), CloseDate = new DateTime(2017,3,19), Runtime = "1 hour 50 minutes with no intermission" },
                new BroadwayShow() { Name = "Brain Candy Live!", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,3,4), CloseDate = new DateTime(2017,3,4), Runtime = "Two hours with an intermission" },
                new BroadwayShow() { Name = "The Illusionists – Live From Broadway", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,2,21), CloseDate = new DateTime(2017,2,26), Runtime = "Two hours with an intermission" },
                new BroadwayShow() { Name = "Men are from Mars – Women are from Venus Live!", Theater = "Broadway Playhouse", OpenDate = new DateTime(2017,2,14), CloseDate = new DateTime(2017,3,5), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "The Bodyguard", Theater = "Oriental Theatre", OpenDate = new DateTime(2017,1,31), CloseDate = new DateTime(2017,2,12), Runtime = "2 hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "The Phantom of The Opera", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,12,14), CloseDate = new DateTime(2017,1,8), Runtime = "2 hours and 45 minutes with an intermission" },
                new BroadwayShow() { Name = "The Curious Incident of the Dog in the Night-Time", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,12,6), CloseDate = new DateTime(2016,12,24), Runtime = "2 hours 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Finding Neverland", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,11,22), CloseDate = new DateTime(2016,12,4), Runtime = "2 hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Stomp", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,11,16), CloseDate = new DateTime(2017,1,1), Runtime = "1 hour and 45 minutes with no intermission" },
                new BroadwayShow() { Name = "A Charlie Brown Christmas", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,11,11), CloseDate = new DateTime(2017,1,8), Runtime = "45 minutes with no intermission" },
                new BroadwayShow() { Name = "Annie", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,11,9), CloseDate = new DateTime(2016,11,13), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Fun Home", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,11,2), CloseDate = new DateTime(2016,11,13), Runtime = "1 hour and 40 minutes with no intermission" },
                new BroadwayShow() { Name = "Graeme of Thrones", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,11,1), CloseDate = new DateTime(2016,11,13), Runtime = "Approximately two hours and 10 minutes with an intermission" },
                new BroadwayShow() { Name = "Hamilton", Theater = "CIBC Theatre", OpenDate = new DateTime(2016,9,27), CloseDate = new DateTime(2020,1,5), Runtime = "2 hours and 45 minutes with an intermission" },
                new BroadwayShow() { Name = "Kinky Boots", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,8,30), CloseDate = new DateTime(2016,9,4), Runtime = "Two hours and twenty minutes with one intermission" },
                new BroadwayShow() { Name = "Disney’s Newsies", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,7,28), CloseDate = new DateTime(2016,8,7), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Schoolhouse Rock Live!", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,7,8), CloseDate = new DateTime(2016,8,14), Runtime = "Approximately 50 minutes with no intermission" },
                new BroadwayShow() { Name = "The Book of Mormon", Theater = "The PrivateBank Theatre", OpenDate = new DateTime(2016,6,29), CloseDate = new DateTime(2016,8,14), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "The SpongeBob Musical", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,6,7), CloseDate = new DateTime(2016,7,10), Runtime = "2 hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "The Sound of Music", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,6,7), CloseDate = new DateTime(2016,6,19), Runtime = "2 hours and 30 minutes with one intermission" },
                new BroadwayShow() { Name = "Disney’s Beauty and the Beast", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,5,24), CloseDate = new DateTime(2016,5,29), Runtime = "2 hours and 30 minutes with one intermission" },
                new BroadwayShow() { Name = "Chicago", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,5,10), CloseDate = new DateTime(2016,5,15), Runtime = "2 hours and 30 minutes with one intermission" },
                new BroadwayShow() { Name = "Disenchanted!", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,5,10), CloseDate = new DateTime(2016,6,5), Runtime = "Approximately 95 minutes with no intermission" },
                new BroadwayShow() { Name = "Bullets Over Broadway", Theater = "The PrivateBank Theatre", OpenDate = new DateTime(2016,4,19), CloseDate = new DateTime(2016,5,1), Runtime = "2 hours and 30 minutes with one intermission" },
                new BroadwayShow() { Name = "One-Man Star Wars Trilogy", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,4,19), CloseDate = new DateTime(2016,4,24), Runtime = "Approximately 75 minutes with no intermission" },
                new BroadwayShow() { Name = "Riverdance – The 20th Anniversary World Tour", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,4,5), CloseDate = new DateTime(2016,4,10), Runtime = "2 hours 10 minutes with one intermission" },
                new BroadwayShow() { Name = "Matilda The Musical", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,3,22), CloseDate = new DateTime(2016,4,10), Runtime = "Two hours and 40 minutes with an intermission" },
                new BroadwayShow() { Name = "Magic Tree House: A Night In New Orleans", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,3,19), CloseDate = new DateTime(2016,4,17), Runtime = "Approximately one hour with no intermission" },
                new BroadwayShow() { Name = "42nd Street", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2016,3,8), CloseDate = new DateTime(2016,3,20), Runtime = "2 hours and 30 minutes with one intermission" },
                new BroadwayShow() { Name = "If/Then", Theater = "Oriental Theatre", OpenDate = new DateTime(2016,2,23), CloseDate = new DateTime(2016,3,6), Runtime = "Two hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Cabaret", Theater = "The PrivateBank Theatre", OpenDate = new DateTime(2016,2,9), CloseDate = new DateTime(2016,2,21), Runtime = "2 hours 30 minutes with one intermission" },
                new BroadwayShow() { Name = "Men Are From Mars, Women Are From Venus Live!", Theater = "Broadway Playhouse", OpenDate = new DateTime(2016,2,9), CloseDate = new DateTime(2016,2,21), Runtime = "2 hours with an intermission" },
                new BroadwayShow() { Name = "Disney Presents The Lion King", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,12,2), CloseDate = new DateTime(2016,1,17), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Beautiful – The Carole King Musical", Theater = "Oriental Theatre", OpenDate = new DateTime(2015,12,1), CloseDate = new DateTime(2016,2,21), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Potted Potter: The Unauthorized Harry Experience", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,12,1), CloseDate = new DateTime(2016,1,10), Runtime = "One hour and 20 minutes with no intermission" },
                new BroadwayShow() { Name = "Sherlock Holmes", Theater = "Oriental Theatre", OpenDate = new DateTime(2015,11,24), CloseDate = new DateTime(2015,11,29), Runtime = "Two hours and 15 minutes with one intermission." },
                new BroadwayShow() { Name = "A Charlie Brown Christmas", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,11,14), CloseDate = new DateTime(2016,1,3), Runtime = "45 minutes with no intermission" },
                new BroadwayShow() { Name = "Mamma Mia!", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,11,10), CloseDate = new DateTime(2015,11,15), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Unspeakable", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,10,6), CloseDate = new DateTime(2015,11,8), Runtime = "Two and a half hours with an intermission" },
                new BroadwayShow() { Name = "A Gentleman’s Guide to Love & Murder", Theater = "Bank of America Theatre", OpenDate = new DateTime(2015,9,29), CloseDate = new DateTime(2015,10,11), Runtime = "Two hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "Dirty Dancing – The Classic Story On Stage", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,8,18), CloseDate = new DateTime(2015,8,30), Runtime = "2 hours 15 minutes including a 20-minute intermission." },
                new BroadwayShow() { Name = "Pippin", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,7,29), CloseDate = new DateTime(2015,8,9), Runtime = "2 hours and 35 minutes with an intermission" },
                new BroadwayShow() { Name = "Fancy Nancy The Musical", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,7,11), CloseDate = new DateTime(2015,8,23), Runtime = "55 minutes with no intermission" },
                new BroadwayShow() { Name = "Kinky Boots", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,7,7), CloseDate = new DateTime(2015,7,26), Runtime = "2 hours and 20 minutes with an intermission" },
                new BroadwayShow() { Name = "Once", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,6,2), CloseDate = new DateTime(2015,6,7), Runtime = "Two hours and 25 minutes with an intermission" },
                new BroadwayShow() { Name = "Rain: A Tribute to the Beatles", Theater = "Bank of America Theatre", OpenDate = new DateTime(2015,5,20), CloseDate = new DateTime(2015,5,24), Runtime = "Two hours with an intermission" },
                new BroadwayShow() { Name = "Jersey Boys", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,5,12), CloseDate = new DateTime(2015,5,24), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Disney’s Beauty and the Beast", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,3,25), CloseDate = new DateTime(2015,3,29), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Annaleigh Ashford – Lost in the Stars", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,3,21), CloseDate = new DateTime(2015,3,21), Runtime = "90 minutes with no intermission" },
                new BroadwayShow() { Name = "The Illusionists – Witness The Impossible™", Theater = "Cadillac Palace Theatre", OpenDate = new DateTime(2015,3,10), CloseDate = new DateTime(2015,3,22), Runtime = "Two hours with an intermission" },
                new BroadwayShow() { Name = "For The Record Presents Dear John Hughes", Theater = "Broadway Playhouse", OpenDate = new DateTime(2015,3,5), CloseDate = new DateTime(2015,3,15), Runtime = "One hour and 55 minutes with an intermission" },
                new BroadwayShow() { Name = "The Book of Mormon", Theater = "Bank of America Theatre", OpenDate = new DateTime(2015,2,25), CloseDate = new DateTime(2015,5,17), Runtime = "Two hours and 30 minutes with an intermission" },
                new BroadwayShow() { Name = "Stomp", Theater = "Bank of America Theatre", OpenDate = new DateTime(2015,1,20), CloseDate = new DateTime(2015,1,25), Runtime = "One hour and 45 minutes with no intermission" }
            };
        }
    }
}